baseURL = 'https://martinkuzma.github.io/'
languageCode = 'en-us'
title = "Martin's inner Cosmos"

theme= "hugo-coder"

[markup]
  [markup.goldmark]
  renderer.unsafe=true
[pagination]
pagerSize = 6

[params]
author = "Martin Kuzma"
#info = ["Developer DevOps", "Magician"]
since = 2025
dateFormat = "January 2, 2006"
colorScheme = "auto"
#gravatar = "kuzma_819@hotmail.com"
maxSeeAlsoItems = 5
customCSS=["css/custom.css"]
customJS=["js/3davatar.min.js"]

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[languages.en]
languageName = ":uk:"

[[languages.en.menu.main]]
name = "About"
weight = 1
url = "about/"

[[languages.en.menu.main]]
name = "Blog"
weight = 2
url = "posts/"

#[[languages.en.menu.main]]
#name = "Contact me"
#weight = 5
#url = "contact/"

[[params.social]]
name = "Github"
icon = "fa-brands fa-github fa-2x"
weight = 1
url = "https://github.com/MartinKuzma"

[[params.social]]
name = "LinkedIn"
icon = "fa-brands fa-linkedin fa-2x"
weight = 4
url = "https://www.linkedin.com/in/martinkuzma/"